### PR TITLE
CDPT-2223 Update logo for heartbeat and test version modals

### PR DESCRIPTION
**Pull request by EarthlingDavey**

### CODE REVIEW

**Comment by wilson1000** [comment]
Do you have a representation of the layout change, if there is one?

**Comment by wilson1000** [comment]
@EarthlingDavey comment above, cheers mate 👍

**Comment by EarthlingDavey** [comment]
Thanks for reviewing, there is no change to layout. 

I found myself resizing the image to get the paragraph text to position correctly, underneath the image.

Clearing float on the paragraph makes it always sit under the image.

**Review by wilson1000 — APPROVED** [review]
Nice mate... there is also a crest on the login page. We can do that later 😄 

Screenshot 2024-10-30 at 12 06 50

**Comment by wilson1000** [comment]
One more thing, can we get a base64 representation of this crest, instead of loading it through the URL? We can maybe save this in CSS and call a class with sizes to show it. 
**What do you think**?

**Comment by EarthlingDavey** [comment]
Good spot! Are you ok with me creating a new svg for now and revisiting changing it to base64 post migration?

**Review by wilson1000 — APPROVED** [review]

**Pull request merged**
