### PR TITLE
Add wp offload media license

### PR DESCRIPTION
**Pull request by wilson1000**
Passes the new WP Offload Media Pro license key through to deployments

### CODE REVIEW

**Comment by wilson1000** [comment]
> this guide

**Comment by wilson1000** [comment]
> To get the package will you follow something like [this guide](https://deliciousbrains.com/wp-migrate-db-pro/doc/installing-via-composer/) or use an MoJ composer repository?

Hey @EarthlingDavey - we have the API key stored in this repo's secret. We can install the pro version and then use the key to activate it, just like we do with Notify. There's no need to use composer to authenticate.

**Comment by EarthlingDavey** [comment]
I don't mind, I can make an entry in [pp-satis-config](https://github.com/ministryofjustice/pp-satis-config). 

I suppose the only downside of doing it that way is... we need to edit the repo for every version update.

**Comment by wilson1000** [comment]
> we need to edit the repo for every version update.

Yes, it's a terrible downside. The trouble we have right now is the procurers haven't sent us login creds for WP Offload Media. If we use the method you suggest we can mitigate updating the repo... I like that a lot better 👍

**Comment by EarthlingDavey** [comment]
Hi @wilson1000 - sorry about the delay. Trying to trouble shoot the broken `.tf` builds.

What do you reckon, should this be on hold until we have logins or a composer username/password pair from the procurers?

**Pull request closed without merging**
